/**
 * Curated suggestion shortlists shared by every editor control with a
 * searchable recommended list. Keeping a single source for each list prevents
 * the controls from drifting. Modeled on stateFilters.ts.
 *
 * The Pinia registries store merges these curated lists with the exhaustive
 * lists served by the backend /api/* endpoints. When the API is unavailable
 * these lists keep the GUI usable.
 */

/**
 * Curated material shortlist. One copy, consolidated from the former
 * materials.json asset plus the inline MATERIAL_SUGGESTIONS in
 * SkillEditorPage.vue.
 */
export const MATERIAL_SUGGESTIONS: string[] = [
  'minecraft:iron_pickaxe',
  'minecraft:iron_axe',
  'minecraft:iron_shovel',
  'minecraft:iron_hoe',
  'minecraft:iron_sword',
  'minecraft:diamond_pickaxe',
  'minecraft:diamond_axe',
  'minecraft:diamond_shovel',
  'minecraft:diamond_hoe',
  'minecraft:diamond_sword',
  'minecraft:netherite_pickaxe',
  'minecraft:netherite_axe',
  'minecraft:netherite_shovel',
  'minecraft:netherite_hoe',
  'minecraft:netherite_sword',
  'minecraft:stone_pickaxe',
  'minecraft:stone_axe',
  'minecraft:stone_shovel',
  'minecraft:stone_hoe',
  'minecraft:stone_sword',
  'minecraft:golden_pickaxe',
  'minecraft:golden_axe',
  'minecraft:golden_shovel',
  'minecraft:golden_hoe',
  'minecraft:golden_sword',
  'minecraft:wooden_pickaxe',
  'minecraft:wooden_axe',
  'minecraft:wooden_shovel',
  'minecraft:wooden_hoe',
  'minecraft:wooden_sword',
  'minecraft:shield',
  'minecraft:bow',
  'minecraft:crossbow',
  'minecraft:trident',
  'minecraft:fishing_rod',
  'minecraft:shears',
  'minecraft:flint_and_steel',
  'minecraft:elytra',
  'minecraft:turtle_helmet',
  'minecraft:leather_helmet',
  'minecraft:leather_chestplate',
  'minecraft:leather_leggings',
  'minecraft:leather_boots',
  'minecraft:chainmail_helmet',
  'minecraft:chainmail_chestplate',
  'minecraft:chainmail_leggings',
  'minecraft:chainmail_boots',
  'minecraft:iron_helmet',
  'minecraft:iron_chestplate',
  'minecraft:iron_leggings',
  'minecraft:iron_boots',
  'minecraft:diamond_helmet',
  'minecraft:diamond_chestplate',
  'minecraft:diamond_leggings',
  'minecraft:diamond_boots',
  'minecraft:netherite_helmet',
  'minecraft:netherite_chestplate',
  'minecraft:netherite_leggings',
  'minecraft:netherite_boots',
  'minecraft:iron_ingot',
  'minecraft:gold_ingot',
  'minecraft:diamond',
  'minecraft:emerald',
  'minecraft:netherite_ingot',
  'minecraft:netherite_scrap',
  'minecraft:coal',
  'minecraft:charcoal',
  'minecraft:redstone',
  'minecraft:lapis_lazuli',
  'minecraft:copper_ingot',
  'minecraft:raw_iron',
  'minecraft:raw_gold',
  'minecraft:raw_copper',
  'minecraft:stick',
  'minecraft:arrow',
  'minecraft:bone',
  'minecraft:bone_meal',
  'minecraft:book',
  'minecraft:enchanted_book',
  'minecraft:experience_bottle',
  'minecraft:potion',
  'minecraft:apple',
  'minecraft:golden_apple',
  'minecraft:enchanted_golden_apple',
  'minecraft:bread',
  'minecraft:cooked_beef',
  'minecraft:cooked_porkchop',
  'minecraft:cooked_chicken',
  'minecraft:cooked_cod',
  'minecraft:cooked_salmon',
  'minecraft:carrot',
  'minecraft:potato',
  'minecraft:baked_potato',
  'minecraft:beetroot',
  'minecraft:sugar',
  'minecraft:cake',
  'minecraft:cookie',
  'minecraft:pumpkin_pie',
  'minecraft:beetroot_soup',
  'minecraft:mushroom_stew',
  'minecraft:suspicious_stew',
  'minecraft:stone',
  'minecraft:cobblestone',
  'minecraft:andesite',
  'minecraft:diorite',
  'minecraft:granite',
  'minecraft:deepslate',
  'minecraft:tuff',
  'minecraft:calcite',
  'minecraft:dirt',
  'minecraft:grass_block',
  'minecraft:podzol',
  'minecraft:mycelium',
  'minecraft:sand',
  'minecraft:red_sand',
  'minecraft:gravel',
  'minecraft:snow_block',
  'minecraft:ice',
  'minecraft:packed_ice',
  'minecraft:blue_ice',
  'minecraft:obsidian',
  'minecraft:crying_obsidian',
  'minecraft:bedrock',
  'minecraft:netherrack',
  'minecraft:soul_sand',
  'minecraft:soul_soil',
  'minecraft:basalt',
  'minecraft:blackstone',
  'minecraft:end_stone',
  'minecraft:prismarine',
  'minecraft:prismarine_bricks',
  'minecraft:dark_prismarine',
  'minecraft:prismarine_shard',
  'minecraft:prismarine_crystals',
  'minecraft:sea_lantern',
  'minecraft:oak_log',
  'minecraft:spruce_log',
  'minecraft:birch_log',
  'minecraft:jungle_log',
  'minecraft:acacia_log',
  'minecraft:dark_oak_log',
  'minecraft:mangrove_log',
  'minecraft:cherry_log',
  'minecraft:oak_planks',
  'minecraft:spruce_planks',
  'minecraft:birch_planks',
  'minecraft:jungle_planks',
  'minecraft:acacia_planks',
  'minecraft:dark_oak_planks',
  'minecraft:mangrove_planks',
  'minecraft:cherry_planks',
  'minecraft:iron_block',
  'minecraft:gold_block',
  'minecraft:diamond_block',
  'minecraft:emerald_block',
  'minecraft:netherite_block',
  'minecraft:copper_block',
  'minecraft:redstone_block',
  'minecraft:lapis_block',
  'minecraft:coal_block',
  'minecraft:iron_ore',
  'minecraft:gold_ore',
  'minecraft:diamond_ore',
  'minecraft:emerald_ore',
  'minecraft:copper_ore',
  'minecraft:redstone_ore',
  'minecraft:lapis_ore',
  'minecraft:coal_ore',
  'minecraft:deepslate_iron_ore',
  'minecraft:deepslate_gold_ore',
  'minecraft:deepslate_diamond_ore',
  'minecraft:deepslate_emerald_ore',
  'minecraft:deepslate_copper_ore',
  'minecraft:deepslate_redstone_ore',
  'minecraft:deepslate_lapis_ore',
  'minecraft:deepslate_coal_ore',
  'minecraft:nether_gold_ore',
  'minecraft:nether_quartz_ore',
  'minecraft:ancient_debris',
  'minecraft:furnace',
  'minecraft:blast_furnace',
  'minecraft:smoker',
  'minecraft:campfire',
  'minecraft:soul_campfire',
  'minecraft:crafting_table',
  'minecraft:enchanting_table',
  'minecraft:anvil',
  'minecraft:grindstone',
  'minecraft:smithing_table',
  'minecraft:brewing_stand',
  'minecraft:cauldron',
  'minecraft:beacon',
  'minecraft:conduit',
  'minecraft:ender_chest',
  'minecraft:chest',
  'minecraft:barrel',
  'minecraft:shulker_box',
  'minecraft:hopper',
  'minecraft:dispenser',
  'minecraft:dropper',
  'minecraft:piston',
  'minecraft:sticky_piston',
  'minecraft:observer',
  'minecraft:composter',
  'minecraft:jukebox',
  'minecraft:note_block',
  'minecraft:lectern',
  'minecraft:loom',
  'minecraft:cartography_table',
  'minecraft:fletching_table',
  'minecraft:stonecutter',
  'minecraft:bell',
  'minecraft:lantern',
  'minecraft:soul_lantern',
  'minecraft:torch',
  'minecraft:soul_torch',
  'minecraft:redstone_torch',
  'minecraft:ender_pearl',
  'minecraft:ender_eye',
  'minecraft:blaze_rod',
  'minecraft:blaze_powder',
  'minecraft:ghast_tear',
  'minecraft:magma_cream',
  'minecraft:slime_ball',
  'minecraft:ender_dragon',
  'minecraft:shulker_shell',
  'minecraft:popped_chorus_fruit',
  'minecraft:chorus_fruit',
  'minecraft:nautilus_shell',
  'minecraft:heart_of_the_sea',
  'minecraft:scute',
  'minecraft:armadillo_scute',
  'minecraft:feather',
  'minecraft:leather',
  'minecraft:rabbit_hide',
  'minecraft:spider_eye',
  'minecraft:fermented_spider_eye',
  'minecraft:golden_carrot',
  'minecraft:glistering_melon_slice',
  'minecraft:rotten_flesh',
  'minecraft:gunpowder',
  'minecraft:string',
  'minecraft:paper',
  'minecraft:map',
  'minecraft:compass',
  'minecraft:recovery_compass',
  'minecraft:clock',
  'minecraft:spyglass',
  'minecraft:totem_of_undying',
  'minecraft:name_tag',
  'minecraft:saddle',
  'minecraft:lead',
  'minecraft:ink_sac',
  'minecraft:glow_ink_sac',
  'minecraft:cocoa_beans',
  'minecraft:red_dye',
  'minecraft:green_dye',
  'minecraft:blue_dye',
  'minecraft:purple_dye',
  'minecraft:cyan_dye',
  'minecraft:yellow_dye',
  'minecraft:orange_dye',
  'minecraft:pink_dye',
  'minecraft:brown_dye',
  'minecraft:black_dye',
  'minecraft:white_dye',
  'minecraft:light_gray_dye',
  'minecraft:gray_dye',
  'minecraft:lime_dye',
  'minecraft:light_blue_dye',
  'minecraft:magenta_dye',
  'minecraft:nether_star',
  'minecraft:dragon_breath',
  'minecraft:firework_rocket',
  'minecraft:firework_star',
  'minecraft:music_disc_13',
  'minecraft:music_disc_cat',
  'minecraft:music_disc_blocks',
  'minecraft:music_disc_chirp',
  'minecraft:music_disc_far',
  'minecraft:music_disc_mall',
  'minecraft:music_disc_mellohi',
  'minecraft:music_disc_stal',
  'minecraft:music_disc_strad',
  'minecraft:music_disc_ward',
  'minecraft:music_disc_11',
  'minecraft:music_disc_wait',
  'minecraft:music_disc_otherside',
  'minecraft:music_disc_5',
  'minecraft:music_disc_pigstep',
  'minecraft:music_disc_relic',
  'minecraft:egg',
  'minecraft:snowball',
  'minecraft:wheat',
  'minecraft:wheat_seeds',
  'minecraft:melon_slice',
  'minecraft:pumpkin',
  'minecraft:carved_pumpkin',
  'minecraft:jack_o_lantern',
  'minecraft:sweet_berries',
  'minecraft:glow_berries',
  'minecraft:kelp',
  'minecraft:dried_kelp',
  'minecraft:bamboo',
  'minecraft:sugar_cane',
  'minecraft:cactus',
  'minecraft:vine',
  'minecraft:glow_lichen',
  'minecraft:spore_blossom',
  'minecraft:flower_pot',
  'minecraft:bucket',
  'minecraft:water_bucket',
  'minecraft:lava_bucket',
  'minecraft:milk_bucket',
  'minecraft:powder_snow_bucket',
  'minecraft:cod_bucket',
  'minecraft:salmon_bucket',
  'minecraft:pufferfish_bucket',
  'minecraft:tropical_fish_bucket',
  'minecraft:axolotl_bucket',
  'minecraft:tadpole_bucket',
  'minecraft:glass',
  'minecraft:glass_pane',
  'minecraft:white_stained_glass',
  'minecraft:orange_stained_glass',
  'minecraft:magenta_stained_glass',
  'minecraft:light_blue_stained_glass',
  'minecraft:yellow_stained_glass',
  'minecraft:lime_stained_glass',
  'minecraft:pink_stained_glass',
  'minecraft:gray_stained_glass',
  'minecraft:light_gray_stained_glass',
  'minecraft:cyan_stained_glass',
  'minecraft:purple_stained_glass',
  'minecraft:blue_stained_glass',
  'minecraft:brown_stained_glass',
  'minecraft:green_stained_glass',
  'minecraft:red_stained_glass',
  'minecraft:black_stained_glass',
  'minecraft:terracotta',
  'minecraft:white_terracotta',
  'minecraft:orange_terracotta',
  'minecraft:magenta_terracotta',
  'minecraft:light_blue_terracotta',
  'minecraft:yellow_terracotta',
  'minecraft:lime_terracotta',
  'minecraft:pink_terracotta',
  'minecraft:gray_terracotta',
  'minecraft:light_gray_terracotta',
  'minecraft:cyan_terracotta',
  'minecraft:purple_terracotta',
  'minecraft:blue_terracotta',
  'minecraft:brown_terracotta',
  'minecraft:green_terracotta',
  'minecraft:red_terracotta',
  'minecraft:black_terracotta',
  'minecraft:brick',
  'minecraft:bricks',
  'minecraft:nether_brick',
  'minecraft:nether_bricks',
  'minecraft:red_nether_bricks',
  'minecraft:end_stone_bricks',
  'minecraft:stone_bricks',
  'minecraft:mossy_stone_bricks',
  'minecraft:cracked_stone_bricks',
  'minecraft:chiseled_stone_bricks',
  'minecraft:mossy_cobblestone',
  'minecraft:honeycomb',
  'minecraft:honey_block',
  'minecraft:honeycomb_block',
  'minecraft:slime_block',
  'minecraft:tnt',
  'minecraft:tnt_minecart',
  'minecraft:rail',
  'minecraft:powered_rail',
  'minecraft:detector_rail',
  'minecraft:activator_rail',
  'minecraft:minecart',
  'minecraft:chest_minecart',
  'minecraft:hopper_minecart',
  'minecraft:furnace_minecart',
  'minecraft:oak_boat',
  'minecraft:spruce_boat',
  'minecraft:birch_boat',
  'minecraft:jungle_boat',
  'minecraft:acacia_boat',
  'minecraft:dark_oak_boat',
  'minecraft:mangrove_boat',
  'minecraft:cherry_boat',
  'minecraft:bamboo_raft',
  'minecraft:painting',
  'minecraft:item_frame',
  'minecraft:glow_item_frame',
  'minecraft:armor_stand',
  'minecraft:writable_book',
  'minecraft:written_book',
  'minecraft:flower_banner_pattern',
  'minecraft:creeper_banner_pattern',
  'minecraft:skull_banner_pattern',
  'minecraft:mojang_banner_pattern',
  'minecraft:globe_banner_pattern',
  'minecraft:piglin_banner_pattern',
  'minecraft:flow_banner_pattern',
  'minecraft:guster_banner_pattern',
  'minecraft:field_masoned_banner_pattern',
  'minecraft:bordure_indented_banner_pattern',
  'minecraft:snout_banner_pattern',
  'minecraft:barrier',
  'minecraft:command_block',
  'minecraft:structure_block',
  'minecraft:structure_void',
  'minecraft:light',
  'minecraft:debug_stick',
  'minecraft:knowledge_book',
  'minecraft:spawner',
  'minecraft:trial_spawner',
  'minecraft:vault',
  'minecraft:breeze_rod',
  'minecraft:heavy_core',
  'minecraft:mace',
];

/**
 * Curated tag shortlist for block and item references. Includes the plugin's
 * own custom tags (#c:...) and a handful of useful vanilla tags.
 */
export const TAG_SUGGESTIONS_BASE: string[] = [
  '#c:ores', '#c:stone', '#c:logs', '#c:gems',
  '#minecraft:logs', '#minecraft:planks', '#minecraft:stone_tool_materials',
  '#minecraft:pickaxes', '#minecraft:axes', '#minecraft:shovels', '#minecraft:hoes',
  '#minecraft:coals', '#minecraft:copper_ores', '#minecraft:iron_ores',
  '#minecraft:gold_ores', '#minecraft:diamond_ores', '#minecraft:emerald_ores',
];

/**
 * Curated entity suggestion list for entity references and entity tags. Used
 * by the tags page entity editor and by the target_type state filter.
 */
export const ENTITY_SUGGESTIONS: string[] = [
  '#minecraft:zombies', '#minecraft:skeletons', '#minecraft:undead', '#minecraft:arthropods',
  '#minecraft:raiders', '#minecraft:aquatic', '#minecraft:axolotl_tempt_items',
  'minecraft:zombie', 'minecraft:skeleton', 'minecraft:creeper', 'minecraft:spider',
];

/**
 * Curated sound event shortlist. The backend /api/sounds endpoint serves the
 * full registry; this list keeps the most useful events on top.
 */
export const SOUND_SUGGESTIONS: string[] = [
  'minecraft:entity.experience_orb.pickup', 'minecraft:entity.player.levelup',
  'minecraft:entity.player.attack.crit', 'minecraft:entity.player.attack.strong',
  'minecraft:entity.player.attack.sweep', 'minecraft:entity.player.attack.knockback',
  'minecraft:entity.player.attack.weak', 'minecraft:entity.arrow.shoot',
  'minecraft:entity.arrow.hit', 'minecraft:entity.firework_rocket.blast',
  'minecraft:entity.firework_rocket.twinkle', 'minecraft:entity.firework_rocket.large_blast',
  'minecraft:entity.firework_rocket.launch', 'minecraft:entity.generic.explode',
  'minecraft:entity.lightning_bolt.thunder', 'minecraft:entity.lightning_bolt.impact',
  'minecraft:entity.wither.spawn', 'minecraft:entity.wither.death',
  'minecraft:entity.wither.shoot', 'minecraft:entity.ender_dragon.death',
  'minecraft:entity.ender_dragon.growl', 'minecraft:entity.dragon_fireball.explode',
  'minecraft:item.trident.thunder', 'minecraft:item.trident.riptide_1',
  'minecraft:item.trident.riptide_2', 'minecraft:item.trident.riptide_3',
  'minecraft:block.anvil.land', 'minecraft:block.anvil.place',
  'minecraft:block.anvil.break', 'minecraft:block.anvil.destroy',
  'minecraft:block.anvil.fall', 'minecraft:block.anvil.hit',
  'minecraft:block.anvil.step', 'minecraft:block.anvil.use',
  'minecraft:block.brewing_stand.brew', 'minecraft:block.chest.open',
  'minecraft:block.chest.close', 'minecraft:block.ender_chest.open',
  'minecraft:block.ender_chest.close', 'minecraft:block.furnace.fire_crackle',
  'minecraft:block.note_block.bell', 'minecraft:block.note_block.chime',
  'minecraft:block.note_block.flute', 'minecraft:block.note_block.guitar',
  'minecraft:block.note_block.harp', 'minecraft:block.note_block.hat',
  'minecraft:block.note_block.basedrum', 'minecraft:block.note_block.snare',
  'minecraft:block.note_block.pling', 'minecraft:block.note_block.xylophone',
  'minecraft:block.note_block.iron_xylophone', 'minecraft:block.note_block.cow_bell',
  'minecraft:block.note_block.didgeridoo', 'minecraft:block.note_block.bit',
  'minecraft:block.note_block.banjo', 'minecraft:ui.button.click',
  'minecraft:ui.toast.in', 'minecraft:ui.toast.out', 'minecraft:ui.toast.challenge_complete',
];

/**
 * Curated particle shortlist. The backend /api/particles endpoint serves the
 * full registry; this list keeps the most useful particles on top.
 */
export const PARTICLE_SUGGESTIONS: string[] = [
  'minecraft:flame', 'minecraft:smoke', 'minecraft:large_smoke', 'minecraft:campfire_cosy_smoke',
  'minecraft:campfire_signal_smoke', 'minecraft:cloud', 'minecraft:crit', 'minecraft:enchanted_hit',
  'minecraft:enchant', 'minecraft:dragon_breath', 'minecraft:end_rod', 'minecraft:explosion',
  'minecraft:explosion_emitter', 'minecraft:firework', 'minecraft:glow', 'minecraft:glow_squid_ink',
  'minecraft:heart', 'minecraft:happy_villager', 'minecraft:angry_villager', 'minecraft:instant_effect',
  'minecraft:effect', 'minecraft:item_slime', 'minecraft:item_snowball', 'minecraft:lava',
  'minecraft:dripping_lava', 'minecraft:falling_lava', 'minecraft:landing_lava', 'minecraft:note',
  'minecraft:poof', 'minecraft:portal', 'minecraft:rain', 'minecraft:splash',
  'minecraft:sweep_attack', 'minecraft:totem_of_undying', 'minecraft:witch',
  'minecraft:dripping_water', 'minecraft:falling_water', 'minecraft:bubble', 'minecraft:bubble_pop',
  'minecraft:fishing', 'minecraft:nautilus', 'minecraft:sonic_boom', 'minecraft:sculk_soul',
  'minecraft:sculk_charge', 'minecraft:sculk_charge_pop', 'minecraft:shriek', 'minecraft:trail',
  'minecraft:dust', 'minecraft:dust_color_transition', 'minecraft:vibration',
];
