name: skilling
version: '${version}'
main: io.github.chasehuegel.skilling.Skilling
api-version: '1.21'
load: POSTWORLD

commands:
  skills:
    description: "View skills and manage progression"
    usage: "/skills [subcommand] [args]"
    aliases: [skill]
